---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-keda

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: openshift-custom-metrics-autoscaler-operator
resources:
  - ../../base
