apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 'custom-metrics-autoscaler-operator'
  namepsace: openshift-keda
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
